<a href="https://colab.research.google.com/github/saisushanth97/ai-engineer-journey/blob/main/00_customer_recontact_prediction/customer_recontact_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("bank.csv",sep=";")

In [2]:
df.shape

(4521, 17)

In [3]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [6]:
df.describe(include="all")

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
count,4521.000000,4521,4521,4521,4521,4521.000000,4521,4521,4521,4521.000000,4521,4521.000000,4521.000000,4521.000000,4521.000000,4521,4521
unique,NaN,12,3,4,2,NaN,2,2,3,NaN,12,NaN,NaN,NaN,NaN,4,2
top,NaN,management,married,secondary,no,NaN,yes,no,cellular,NaN,may,NaN,NaN,NaN,NaN,unknown,no
freq,NaN,969,2797,2306,4445,NaN,2559,3830,2896,NaN,1398,NaN,NaN,NaN,NaN,3705,4000
mean,41.170095,NaN,NaN,NaN,NaN,1422.657819,NaN,NaN,NaN,15.915284,NaN,263.961292,2.793630,39.766645,0.542579,NaN,NaN
std,10.576211,NaN,NaN,NaN,NaN,3009.638142,NaN,NaN,NaN,8.247667,NaN,259.856633,3.109807,100.121124,1.693562,NaN,NaN
min,19.000000,NaN,NaN,NaN,NaN,-3313.000000,NaN,NaN,NaN,1.000000,NaN,4.000000,1.000000,-1.000000,0.000000,NaN,NaN
25%,33.000000,NaN,NaN,NaN,NaN,69.000000,NaN,NaN,NaN,9.000000,NaN,104.000000,1.000000,-1.000000,0.000000,NaN,NaN
50%,39.000000,NaN,NaN,NaN,NaN,444.000000,NaN,NaN,NaN,16.000000,NaN,185.000000,2.000000,-1.000000,0.000000,NaN,NaN
75%,49.000000,NaN,NaN,NaN,NaN,1480.000000,NaN,NaN,NaN,21.000000,NaN,329.000000,3.000000,-1.000000,0.000000,NaN,NaN
max,87.000000,NaN,NaN,NaN,NaN,71188.000000,NaN,NaN,NaN,31.000000,NaN,3025.000000,50.000000,871.000000,25.000000,NaN,NaN

In [17]:
df.groupby("y")["duration"].describe()

      count        mean         std   min    25%    50%    75%     max
y
no   4000.0  226.347500  210.313631   4.0   96.0  167.0  283.0  3025.0
yes   521.0  552.742802  390.325805  30.0  260.0  442.0  755.0  2769.0

In [18]:
pd.crosstab(df["pdays"], df["y"], normalize="index")

y            no       yes
pdays
-1     0.909042  0.090958
 1     0.000000  1.000000
 2     1.000000  0.000000
 3     1.000000  0.000000
 5     1.000000  0.000000
...         ...       ...
 687   1.000000  0.000000
 761   0.000000  1.000000
 804   0.000000  1.000000
 808   1.000000  0.000000
 871   1.000000  0.000000

[292 rows x 2 columns]

In [22]:
pd.crosstab([df["job"], df["housing"]],df["y"], normalize="index").sort_values("yes", ascending=False)

y                            no       yes
job           housing
unknown       yes      0.000000  1.000000
student       no       0.734375  0.265625
retired       no       0.738889  0.261111
housemaid     no       0.835616  0.164384
unknown       no       0.837838  0.162162
admin.        no       0.840909  0.159091
unemployed    no       0.842857  0.157143
management    no       0.843348  0.156652
self-employed no       0.852632  0.147368
retired       yes      0.860000  0.140000
technician    no       0.863372  0.136628
services      no       0.863636  0.136364
management    yes      0.884692  0.115308
entrepreneur  yes      0.893617  0.106383
student       yes      0.900000  0.100000
admin.        yes      0.900662  0.099338
blue-collar   no       0.908367  0.091633
technician    yes      0.915094  0.084906
services      yes      0.929825  0.070175
self-employed yes      0.931818  0.068182
entrepreneur  no       0.932432  0.067568
blue-collar   yes      0.933813  0.066187
housemaid     yes      0.948718  0.051282
unemployed    yes      0.965517  0.034483

In [23]:
df.groupby("y")["balance"].agg(
    ["count", "mean", "median", "min", "max"]
)

     count         mean  median   min    max
y
no    4000  1403.211750   419.5 -3313  71188
yes    521  1571.955854   710.0 -1206  26965

In [24]:
df.groupby("y")["balance"].quantile([0.25, 0.75])

y
no   0.25      61.0
     0.75    1407.0
yes  0.25     171.0
     0.75    2160.0
Name: balance, dtype: float64